site_name: IMOS Documentation
site_url: https://sumitagarwal-i1.github.io/imos-documentation/
theme:
  name: material
nav:
  - Home: index.md
  - Install: installation.md
  - Quickstart: getting-started.md
  - Command Reference: commands.md
  - Use Cases: use-cases.md
  - FAQ: faq.md
  - Community: community.md
  - Roadmap: roadmap.md
  - Contributing: contributing.md
  - Changelog: changelog.md
